### ISSUE TITLE
crash when geojson has empty coordinates 

### ISSUE THREAD

**Issue by i4ki** [venicegeo/geojson-go#3]
The geojson below cause a crash when parsing:

```json
{
	"features": [{
		"geometry": {
			"coordinates": [],
			"type": "MultiPolygon"
		},
		"properties": {},
		"type": "Feature"
	}],
	"type": "FeatureCollection"
}
```

**Comment by i4ki** [comment]
Sorry, I just read the "What does it not do well?" section in the README regarding malformed input. Is that such a case? If yes, this means I need to parse the geojson beforehand only to discover it's malformed?

**Comment by jyutzler** [comment]
First of all, I apologize for not responding more promptly to this message. I updated my notifications settings to prevent this from recurring in the future. 

We will take a look at this.
